export const theme = {
  colors: {
    primary: '#2e7d32',
    primaryDark: '#1b5e20',
    lightGreen: '#e8f5e9',
    softAccent: '#c8e6c9',
    accent: '#2e7d32',
    success: '#2e7d32',
    warning: '#f59e0b',
    error: '#dc2626',
    background: '#f5f9f7',
    card: '#ffffff',
    text: '#1f2937',
    textLight: '#6b7280',
    border: '#dcedc8',
    divider: '#eeeeee',
    inputBorder: '#cccccc',
  },
  spacing: {
    xs: 4,
    s: 8,
    sm: 12,
    m: 16,
    l: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    s: 6,
    m: 10,
    l: 16,
    xl: 24,
    round: 9999,
  },
  shadows: {
    soft: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 5,
    }
  },
  typography: {
    fontFamily: 'Segoe UI',
    h1: { fontSize: 24, fontWeight: '700' },
    h2: { fontSize: 19, fontWeight: '700' },
    body: { fontSize: 15, fontWeight: '400' },
    small: { fontSize: 12, fontWeight: '400' },
  },
};
